import json, math
from shapely.geometry import shape, box, Polygon, MultiPolygon, mapping
from shapely.ops import unary_union, transform
from shapely.validation import make_valid

LON0, LAT0 = 10.0, 50.0
def proj(lon, lat):
    l, p = math.radians(lon - LON0), math.radians(lat)
    p1 = math.radians(LAT0)
    k = math.sqrt(2 / (1 + math.sin(p1)*math.sin(p) + math.cos(p1)*math.cos(p)*math.cos(l)))
    return k*math.cos(p)*math.sin(l), k*(math.cos(p1)*math.sin(p) - math.sin(p1)*math.cos(p)*math.cos(l))

cities = json.load(open('cities_ll.json'))
# fit: extent covering cities with margins
pts = [proj(c['lon'], c['lat']) for c in cities]
xs, ys = [p[0] for p in pts], [p[1] for p in pts]
minx, maxx, miny, maxy = min(xs), max(xs), min(ys), max(ys)
W = 1600.0
padL, padR, padT, padB = 0.09, 0.08, 0.10, 0.10
spanx = (maxx-minx); spany = (maxy-miny)
x0 = minx - spanx*padL; x1 = maxx + spanx*padR
y0 = miny - spany*padB; y1 = maxy + spany*padT
S = W/(x1-x0); H = round((y1-y0)*S)
def to_px(lon, lat, z=None):
    x, y = proj(lon, lat)
    return ((x-x0)*S, (y1-y)*S)
view = box(-W*0.6, -H*0.2, W*1.6, H*1.2)
pre = box(-40, 24, 62, 74)

def fix(g): 
    g = make_valid(g)
    return g.buffer(0)
def P(g):
    return transform(lambda x, y, z=None: tuple(zip(*[to_px(a, b) for a, b in zip(x, y)])) if False else _tp(x, y), g)
def _tp(x, y):
    out = [to_px(a, b) for a, b in zip(x, y)]
    return [o[0] for o in out], [o[1] for o in out]

land = fix(shape(json.load(open('land50.json'))['features'][0]['geometry']) if 'features' in json.load(open('land50.json')) else shape(json.load(open('land50.json'))['geometry']))
land = land.intersection(pre)

hist = json.load(open('w1930.json'))['features']
NAME = {'Libya (IT)':'Libya','United Kingdom of Great Britain and Ireland':'United Kingdom','White Russia':'Soviet Union','Armenia':'Soviet Union',
        'Georgia':'Soviet Union','East Prussia':'Germany','Republic of Turkey':'Turkey','Mesopotamia (GB)':'Iraq','Syria (France)':'Syria'}
groups = {}
for f in hist:
    n = f['properties'].get('NAME')
    if not n: continue
    g = fix(shape(f['geometry']))
    if not g.intersects(pre): continue
    n = NAME.get(n, n)
    groups.setdefault(n, []).append(g.intersection(pre))
countries = {n: unary_union(gs) for n, gs in groups.items()}

ne = {f['properties']['name']: f for f in json.load(open('countries50.json'))['features']}
ireland = fix(shape(ne['Ireland']['geometry']))
countries['Irish Free State'] = ireland
countries['United Kingdom'] = countries['United Kingdom'].difference(ireland.buffer(0.02))
saar = Polygon([(6.36,49.46),(6.55,49.17),(6.85,49.15),(7.05,49.12),(7.30,49.12),(7.40,49.20),(7.35,49.45),(7.25,49.62),(6.95,49.64),(6.60,49.62),(6.40,49.55)])
countries['Saar'] = saar
countries['Germany'] = countries['Germany'].difference(saar)

def ring_path(coords):
    pts = list(coords)
    return 'M' + 'L'.join(f'{x:.1f},{y:.1f}' for x, y in pts[:-1]) + 'Z'
def geom_path(g):
    polys = [g] if isinstance(g, Polygon) else [p for p in getattr(g, 'geoms', []) if isinstance(p, Polygon)]
    out = []
    for p in polys:
        if p.area < 1.5: continue
        out.append(ring_path(p.exterior.coords))
        for r in p.interiors:
            if Polygon(r).area > 1.5: out.append(ring_path(r.coords))
    return ''.join(out)
def prep(g, tol=0.45):
    g = fix(P(g))
    g = g.intersection(view)
    return g.simplify(tol, preserve_topology=True)

landp = prep(land)
out_c = []
for n, g in countries.items():
    g = fix(g).intersection(land)
    gp = prep(g)
    if gp.is_empty or gp.area < 3: continue
    big = max(gp.geoms, key=lambda p: p.area) if hasattr(gp, 'geoms') else gp
    rp = big.representative_point()
    out_c.append({'name': n, 'path': geom_path(gp), 'area': round(gp.area), 'label': [round(rp.x), round(rp.y)], '_g': gp})

# greedy coloring
out_c.sort(key=lambda c: -c['area'])
for c in out_c:
    used = {o.get('tint') for o in out_c if 'tint' in o and o['_g'].buffer(3).intersects(c['_g'])}
    c['tint'] = next(i for i in range(6) if i not in used)
for c in out_c: del c['_g']

city_px = {c['id']: [round(v, 1) for v in to_px(c['lon'], c['lat'])] for c in cities}
data = {'width': W, 'height': H, 'projection': {'lon0': LON0, 'lat0': LAT0, 'x0': x0, 'y1': y1, 'scale': S},
        'land': geom_path(landp), 'countries': out_c}
js = ('// Generated by tools/build_map.py from historical-basemaps (1930, GPL-3.0) and Natural Earth (public domain).\n'
      '// Borders adjusted to about 1924: Irish Free State separated, Saar under League administration.\n'
      'window.UPSHIP_MAP_EUROPE = ' + json.dumps(data, separators=(',', ':')) + ';\n')
open('map-europe.js', 'w').write(js)
print('size', len(js)//1024, 'KB', 'H', H, [ (c['name'], c['tint'], c['area']) for c in out_c][:40])
