# Builds js/data/map-europe.js: Europe about 1924, from Natural Earth provinces (public domain).
# Steps: assign1924.py (provinces -> 1924 countries), then mapshaper (dissolve, project, simplify,
# shared borders), then this script (fit to the city area, clip, write SVG paths).
import json, math
from shapely.geometry import shape, box, Polygon, LineString
from shapely.ops import unary_union
LON0, LAT0 = 14.0, 47.0
def proj(lon, lat):
    l, p, p1 = math.radians(lon - LON0), math.radians(lat), math.radians(LAT0)
    k = math.sqrt(2 / (1 + math.sin(p1)*math.sin(p) + math.cos(p1)*math.cos(p)*math.cos(l)))
    return k*math.cos(p)*math.sin(l), k*(math.cos(p1)*math.sin(p) - math.sin(p1)*math.cos(p)*math.cos(l))
cities = json.load(open('cities_ll.json'))
pts = [proj(c['lon'], c['lat']) for c in cities]
xs, ys = [p[0] for p in pts], [p[1] for p in pts]
minx, maxx, miny, maxy = min(xs), max(xs), min(ys), max(ys)
W = 1600.0
sx, sy = maxx-minx, maxy-miny
x0 = minx - sx*0.07; x1 = maxx + sx*0.07; y0 = miny - sy*0.07; y1 = maxy + sy*0.08
S = W/(x1-x0); H = round((y1-y0)*S)
view = box(-W*0.6, -H*0.2, W*1.6, H*1.2)
def px(g):
    from shapely.affinity import affine_transform
    return affine_transform(g, [S, 0, 0, -S, -x0*S, y1*S])
def fmt(coords): return 'L'.join(f'{x:.1f},{y:.1f}' for x, y in coords)
def poly_path(g):
    polys = [g] if isinstance(g, Polygon) else [p for p in getattr(g, 'geoms', []) if isinstance(p, Polygon)]
    out = ''
    for p in polys:
        if p.area < 1.0: continue
        out += 'M' + fmt(list(p.exterior.coords)[:-1]) + 'Z'
        for r in p.interiors:
            if Polygon(r).area >= 1.0: out += 'M' + fmt(list(r.coords)[:-1]) + 'Z'
    return out
def line_path(g):
    lines = [g] if isinstance(g, LineString) else [l for l in getattr(g, 'geoms', []) if isinstance(l, LineString)]
    return ''.join('M' + fmt(l.coords) for l in lines if l.length > 0.5)
countries, allg = [], []
for f in json.load(open('countries_p.json'))['features']:
    g = px(shape(f['geometry'])).buffer(0).intersection(view)
    if g.is_empty or g.area < 2: continue
    allg.append(g)
    big = max(g.geoms, key=lambda p: p.area) if hasattr(g, 'geoms') else g
    rp = big.representative_point()
    countries.append({'name': f['properties']['c'], 'path': poly_path(g), 'area': round(g.area), 'label': [round(rp.x), round(rp.y)], '_g': g})
land = unary_union(allg)
bj = json.load(open('borders_p.json'))
bfeats = bj.get('features') or bj.get('geometries') or [bj]
borders = unary_union([px(shape(f.get('geometry', f))) for f in bfeats]).intersection(view)
countries.sort(key=lambda c: -c['area'])
for c in countries:
    used = {o['tint'] for o in countries if 'tint' in o and o['_g'].buffer(2).intersects(c['_g'])}
    c['tint'] = next(i for i in range(6) if i not in used)
for c in countries: del c['_g']
data = {'width': W, 'height': H, 'projection': {'lon0': LON0, 'lat0': LAT0, 'x0': x0, 'y1': y1, 'scale': S},
        'borders': line_path(borders), 'countries': countries}
open('map-europe.js', 'w').write(
    '// Generated by tools/build_map.py from Natural Earth admin-1 provinces (public domain),\n'
    '// regrouped into approximate 1924 countries by tools/assign1924.py.\n'
    'window.UPSHIP_MAP_EUROPE = ' + json.dumps(data, separators=(',', ':')) + ';\n')
print('KB', len(open('map-europe.js').read())//1024, 'H', H, len(countries))
